# Generated by Django 5.1.6 on 2025-04-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_deliveryjob_deliveryjob_deliveryguy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfull',
            name='lat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userfull',
            name='lon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
